server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ENotarySystem

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:enotary_db}
    username: ${DB_USERNAME:tuyenngduc}
    password: ${DB_PASSWORD:tuyen123}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


jwt:
  secret: ${JWT_SECRET:1912C50BBE349F81043F6BC7A2E440E708C02E4F2A2E38A87049BA5BA9FB19E7B93206AE55412E28449360F0FC25CF1C2626609BA96CAAF05E113DCB759279E4}
  expiration: ${JWT_EXPIRATION:900000} # 15 minutes in ms
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in ms

logging:
  level:
    org.springframework.security: DEBUG
app:
  admin:
    email: ${ADMIN_EMAIL:admin@localhost}
    password: ${ADMIN_PASSWORD:DefaultAdmin@123}